### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Michael-Wheeler**
- Cleaned REST Requests
- Removed UserControllers for now
- Cleaned StravaController TFL Logic
- Renamed TFLClient to TFLConnector

### CODE REVIEW

**Comment by james-goddard12** [comment]
Oi oi

**Comment by Michael-Wheeler** [comment]
Haha, it was cluttering my PR tab so I just went ahead and did it

**Comment by Michael-Wheeler** [comment]
We're all PHP devs now anyway, assuming you're still at Rockar and the NTT hasn't folded without me?

**Comment by james-goddard12** [comment]
I got booted off rockar while I was on holiday, along with bassan

**Comment by james-goddard12** [comment]
and now they've decided to use cinnamon. no one has used cinnamon at rockar
lol

**Comment by Michael-Wheeler** [comment]
Daym, on the bright side, you aren't doing another Cinnamon project. Unless you got another one

**Comment by james-goddard12** [comment]
no idea. i'm benched for now. which is good timing coz i need to recover
from holiday. How's things your end? new job going well?

**Comment by Michael-Wheeler** [comment]
Was that America?

Yeah, going well, I'm wfh in Birmingham this week. It's all vue and PHP and everyone has lot's of experience of both. It's good for learning off people but pretty different than what I'm used to, i.e no one knowing wtf is going on other than the Bassan's

**Pull request merged**
